### ISSUE TITLE
how do i use this program? 

### ISSUE THREAD

**Issue by tommi-fish** [18/SteamIDChecker#1]
how do i go about 'running' this program. 
sorry for being a complete noobie D: 

(win 10)

**Comment by sdkrystian** [comment]
Hey,
All you need a text document of words you want to check named "words" in the same directory as the application. Run the application and you're good.

**Comment by tommi-fish** [comment]
How exactly would I 'run' the application? i've just got the source code ( i think ? ) 
license file
main.cpp
readme.md 
etc etc

there's not an executable or anything like that? did i download the incorrect thing or is there something i completely missing. 

thanks for your reply !

**Comment by 18** [comment]
Whoops! Let me compile it for ya and send it over


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: 5peep <notifications@github.com> Date: 5/26/18  19:52  (GMT-05:00) To: 18/Steam-ID-Checker <Steam-ID-Checker@noreply.github.com> Cc: Krystian S <sdkrystian@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [18/Steam-ID-Checker] how do i use this program? (#1) 
How exactly would I 'run' the application? i've just got the source code ( i think ? )

license file

main.cpp

readme.md

etc etc
there's not an executable or anything like that? did i download the incorrect thing or is there something i completely missing.
thanks for your reply !

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/18/Steam-ID-Checker/issues/1#issuecomment-392295247","url":"https://github.com/18/Steam-ID-Checker/issues/1#issuecomment-392295247","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/18/Steam-ID-Checker","title":"18/Steam-ID-Checker","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/18/Steam-ID-Checker"}},"updates":{"snippets":[{"icon":"PERSON","message":"@5peep in #1: How exactly would I 'run' the application? i've just got the source code ( i think ? ) \r\nlicense file\r\nmain.cpp\r\nreadme.md \r\netc etc\r\n\r\nthere's not an executable or anything like that? did i download the incorrect thing or is there something i completely missing. \r\n\r\nthanks for your reply !  "}],"action":{"name":"View Issue","url":"https://github.com/18/Steam-ID-Checker/issues/1#issuecomment-392295247"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [18/Steam-ID-Checker] how do i use this program?  (#1)",
"sections": [
{
"text": "",
"activityTitle": "**5peep**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@5peep",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"18/Steam-ID-Checker\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"18/Steam-ID-Checker\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/18/Steam-ID-Checker/issues/1#issuecomment-392295247"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 339488507\n}"
}
],
"themeColor": "26292E"
}

**Comment by tommi-fish** [comment]
That would be great, thank you!

**Comment by sdkrystian** [comment]
https://file.town/download/qspw3akr5tptmmcm6cu5315i5 Here is the exe, enjoy :)

**Comment by tommi-fish** [comment]
Thanks, I've tested it and the output seems to be blank,  
It saves a html file which links to the steam profile of the first word in the list?

**Comment by sdkrystian** [comment]
Hey,
What list of words are you using? If the word is taken, it isn't written to
the output.

**Comment by sdkrystian** [comment]
https://file.town/download/qcxmenqjk1yjtodyypzzheoit Here is a version that will write to the file real time. Use this instead.

**Comment by tommi-fish** [comment]
I tested this one out and it seems to be a bit weird. the words i used were;
midmorning
midflight
midfielders
dog
cat
sheep
fly

the first three not being taken currently whereas the last four are. 
the output file simply contained 
"ID: fly" 
and saved a html file of the steam community profile of id/fly

**Comment by sdkrystian** [comment]
Alright, I looks like i messed the code up when I was re-organizing it today. I'll fix it and let you know when its working.

**Comment by tommi-fish** [comment]
Thank you, sorry for being a pain in the ass!

**Comment by sdkrystian** [comment]
Nah, its fine, I need to fix it anyways :D

**Comment by sdkrystian** [comment]
https://file.town/download/srm3cordyvabihqib0kpptkkf Sorry it took so long, made a silly little mistake

**Comment by tommi-fish** [comment]
You didn't take long at all haha, 
It's working great. Thanks a bunch. :-)
